### PR TITLE
Improve test running

### PR DESCRIPTION
**Pull request by KAUTH**
Improve test duration with the `pytest-xdist` plugin

### CODE REVIEW

**Comment by KAUTH** [comment]
@kairoaraujo @MVrachev I can't add you via the reviewers so tagging you. Also. it would be nice to add this to the sprint as well, under the To-Review column.

**Comment by KAUTH** [comment]
@kairoaraujo @MVrachev I fixed the test, but I'm more worried about why it had been failing or why it hadn't been failing before.

In short, `update_snapshot` function gives a type of `Metafile` (from tuf python client) to `snapshot.signed.meta` keys, so we have to assert accordingly in the test. My question is how it passed before? I don't see any recent changes in the tuf client or in the worker on how this is handled.

**Comment by kairoaraujo** [comment]
> @kairoaraujo @MVrachev I fixed the test, but I'm more worried about why it had been failing or why it hadn't been failing before.
> 
> In short, `update_snapshot` function gives a type of `Metafile` (from tuf python client) to `snapshot.signed.meta` keys, so we have to assert accordingly in the test. My question is how it passed before? I don't see any recent changes in the tuf client or in the worker on how this is handle
> 

I think it was using a previous test mock return. 
While using async tests it is not ordered anymore. 

> 
> Also, somehow `coverage` was affected...

That because there is returns in tests. 
Just exclude tests/ from coverage.

**Comment by MVrachev** [comment]
> That because there is returns in tests.
> Just exclude tests/ from coverage.

Yes, this should fix the issue.

**Comment by KAUTH** [comment]
@MVrachev @kairoaraujo Should be ready now!

**Review by kairoaraujo — APPROVED** [review]

**Review by kairoaraujo — APPROVED** [review]

**Comment by KAUTH** [comment]
@kairoaraujo some of the functional tests failed for what seems to be an external reason from GH actions, could you reapprove so that the tests are triggered?

**Review by kairoaraujo — APPROVED** [review]

**Pull request merged**
